import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/app-layout";
import LenisScroll from "@/components/lenis";
import { Toaster } from "@/components/ui/sonner";
import { toast } from 'sonner';
import localFont from "next/font/local";

const borsok = localFont({
  src: "../../public/fonts/boorsok.ttf",
  variable: "--font-borsok",
});
const fredoka = localFont({
  src: "../../public/fonts/Fredoka-VariableFont_wdth,wght.ttf",
  variable: "--font-fredoka",
});
const lilita = localFont({
  src: "../../public/fonts/LilitaOne-Regular.ttf",
  variable: "--font-lilita",
});
const eliane = localFont({
  src: "../../public/fonts/anjaeliane.ttf",
  variable: "--font-eliane",
});
const arial = localFont({
  src: "../../public/fonts/arial-rounded-bold.ttf",
  variable: "--font-arial",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nemuneko Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${borsok.variable} ${fredoka.variable} ${lilita.variable} ${eliane.variable} ${arial.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <AppLayout>

          {children}
        </AppLayout>
      </body>
    </html>
  );
}
